server:
  port: 8099

spring:
  datasource:
#    url: jdbc:mysql://database.back1.hpnu.cn:3306/demo
    url: jdbc:mysql://localhost:3306/demo
    username: root
    password: 248789
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher